---
title: "3D expression patterns with my algorithm"
author: "Mayra L. Ruiz Tejada Segura"
date: "30/01/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r shinyApp, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(shiny)
library(reshape2)
library(plotly)

seed.3d<-readRDS(file="./seed.3dSymCorrected.Rda")
M<-melt(seed.3d)
names(M)<-c("DV",  "LML",  "PA",  "value")

sliceVolLML<-sapply(1:dim(seed.3d)[2], function(x){table(seed.3d[,x,])[2]})
#sliceVolLML[which(!(1:max(positionLML) %in% positionLML))]<-NA
sliceVolDV<-sapply(1:dim(seed.3d)[1], function(x){table(seed.3d[x,,])[2]})
sliceVolPA<-sapply(1:dim(seed.3d)[3], function(x){table(seed.3d[,,x])[2]})

LMLwPred<-read.csv("./LMLwithPredValsandGenex.csv", header=T, row.names = 1, stringsAsFactors = F)
DVwPred<-read.csv("./DVwithPredValsandGenex.csv", header=T, row.names = 1, stringsAsFactors = F)
PAwPred<-read.csv("./PAwithPredValsandGenex.csv", header=T, row.names = 1, stringsAsFactors = F)

#LMLwPred<-read.csv("../fittedDEGs_LML.csv", header=T, row.names = 1, stringsAsFactors = F)
#DVwPred<-read.csv("../fittedDEGs_DV.csv", header=T, row.names = 1, stringsAsFactors = F)
#PAwPred<-read.csv("../fittedDEGs_PA.csv", header=T, row.names = 1, stringsAsFactors = F)

#LMLwPred[LMLwPred<0]<-0
#DVwPred[DVwPred<0]<-0
#PAwPred[PAwPred<0]<-0

ipf3D<-function(seed, targetx, targety, targetz, nodecs){
  h=1
  iter1<-rep(1, length(c(targetx, targety, targetz)))
  iter2<-rep(0, length(c(targetx, targety, targetz)))
  while("FALSE" %in% (round(iter1, nodecs)==round(iter2, nodecs))){
  #while(h<(numIter+1)){
  
    for(i in 1:dim(seed)[1]){
     seed[i,,]<-seed[i,,]*targetx[i]/sum(seed[i,,],na.rm=T)
    }
    
    for(i in 1:dim(seed)[2]){
     seed[,i,]<-seed[,i,]*targety[i]/sum(seed[,i,],na.rm=T)
    }
    
    for(i in 1:dim(seed)[3]){
     seed[,,i]<-seed[,,i]*targetz[i]/sum(seed[,,i],na.rm=T)
    }
    
    if((h %% 2)==0){
      iter2<-c(apply(seed, 1, sum), apply(seed, 2, sum), apply(seed, 3, sum))
    }else{
      iter1<-c(apply(seed, 1, sum), apply(seed, 2, sum), apply(seed, 3, sum))
    }
    h=h+1
  }
  seed[is.na(seed)]<-0 #We can get NA values if targets are 0
  return(seed)
}

ui<-fluidPage(
  titlePanel("Mouse Main Olfactory Epithelium Atlas"),
  mainPanel(plotlyOutput(outputId = "ThreeDStructure")),
  textInput(inputId = "gene", label = "Introduce a gene name", value="Acsm4"),
  plotOutput(outputId = "OneDPlots"),
  plotlyOutput(outputId = "ThreeDPlot"),
  radioButtons("projection", "Slices Projection:",
               c("DV x LML" = "DVxLML",
                 "DV x PA" = "DVxPA",
                 "LML x PA" = "LMLxPA")),
  plotlyOutput(outputId = "ThreeDSlices")
)

server<-function(input, output){
  output$ThreeDStructure<-renderPlotly({
    
    ##Plot shape 

    #x<-list(title="DV") 
    #y<-list(title="LML") 
    #z<-list(title="PA") 

    library(RColorBrewer)
    palette <- colorRampPalette(c("gray"))(n = 1)

    M1<-M[-which(M$value==0),]

    plot_ly(M1, x = ~DV, y = ~LML, z = ~PA, color=1, colors = "gray", marker=c(list(size=1))) %>% hide_colorbar()
  })
  output$OneDPlots<-renderPlot({
    par(mfrow=c(2, 2))
    library(locfit)
    for(axis in c("DV", "PA", "LML")){
      if(input$gene %in% rownames(get(paste(axis, "wPred", sep="")))){
        title<-paste(input$gene, "normalized expression across the", axis, "axis")
        target<-as.numeric(get(paste(axis, "wPred", sep=""))[rownames(get(paste(axis, "wPred", sep="")))==input$gene,])
        plot(target, xlab=paste(axis, "position"), ylab="Normalized gene expression", main=title)
        lines(locfit(target~lp(1:length(target), deg = 2, nn=1)), col="red")
      }
      else{
        plot.new()
        text(0.5, 0.2, paste(input$gene, "was not found in the", axis, "axis dataset"))
      }
    }
  })
  
  output$ThreeDPlot<-renderPlotly({
    
    #normalize by slice volume
    target.LML<-as.numeric(LMLwPred[rownames(LMLwPred)==input$gene,])*sliceVolLML/(sum(sliceVolLML))
    target.PA<-as.numeric(PAwPred[rownames(PAwPred)==input$gene,])*sliceVolPA/(sum(sliceVolPA))
    target.DV<-as.numeric(DVwPred[rownames(DVwPred)==input$gene,])*sliceVolDV/(sum(sliceVolDV))

    target.DV<-target.DV*1000000/sum(target.DV)
    target.LML<-target.LML*1000000/sum(target.LML)
    target.PA<-target.PA*1000000/sum(target.PA)
    
    struc3d<-ipf3D(seed=seed.3d, targetx=target.DV, targety=target.LML, targetz=target.PA, nodecs=0)

    M3=melt(struc3d)
    names(M3)<-c("DV", "LML", "PA", "value")
    M3<-M3[-which(M$value==0),]
    M3$value<-log10(M3$value+1)

    my_palette2 <- colorRampPalette(c("gray", "blue", "yellow", "orange", "red"))(n = 100)
    if(sum(M3$value>0)){
      plot_ly(M3, x = ~DV, y = ~LML, z = ~PA, color = ~value, colors = my_palette2, marker=c(list(size=1.5)))
    }
  })
  
  output$ThreeDSlices<-renderPlotly({
    #normalize by slice volume
    target.LML<-as.numeric(LMLwPred[rownames(LMLwPred)==input$gene,])*sliceVolLML/(sum(sliceVolLML))
    target.PA<-as.numeric(PAwPred[rownames(PAwPred)==input$gene,])*sliceVolPA/(sum(sliceVolPA))
    target.DV<-as.numeric(DVwPred[rownames(DVwPred)==input$gene,])*sliceVolDV/(sum(sliceVolDV))

    target.DV<-target.DV*1000000/sum(target.DV)
    target.LML<-target.LML*1000000/sum(target.LML)
    target.PA<-target.PA*1000000/sum(target.PA)
    
    struc3d<-ipf3D(seed=seed.3d, targetx=target.DV, targety=target.LML, targetz=target.PA, nodecs=0)

    M3=melt(struc3d)
    names(M3)<-c("DV", "LML", "PA", "value")
    M3<-M3[-which(M$value==0),]
    M3$value<-log10(M3$value+1)

    my_palette2 <- colorRampPalette(c("gray", "blue", "yellow", "orange", "red"))(n = 100)

    j=1
    for(i in seq(1, max(M3$PA), 10)){
      mt2<-data.frame(DV=M3$DV[M3$PA==i], LML=M3$LML[M3$PA==i], val=M3$value[M3$PA==i])
      if(sum(mt2$val)==0){
        assign(paste("p", j, sep=""), plot_ly(mt2, x = ~DV, y = ~LML, color = 1, colors = "gray", showlegend=FALSE) %>% layout(xaxis = list(range = c(0, dim(struc3d)[1])), yaxis = list(range = c(0, dim(struc3d)[2]))) %>% hide_colorbar())
      }else{
        assign(paste("p", j, sep=""), plot_ly(mt2, x = ~DV, y = ~LML, color = ~val, colors = my_palette2, showlegend=FALSE) %>% layout(xaxis = list(range = c(0, dim(struc3d)[1])), yaxis = list(range = c(0, dim(struc3d)[2]))) %>% colorbar(limits = c(0,log10(max(struc3d)))) %>% hide_colorbar())
      }
      j=j+1
    }
    varlist<-ls(pattern="p[[:digit:]]")
    plotlistDVxLML<-list()
    
    for(i in 1:length(varlist)){
      plotlistDVxLML[[i]]<-get(varlist[i])
    }
    
    rm(list=varlist)
    j=1
    for(i in seq(1, max(M3$LML), 10)){
      mt2<-data.frame(DV=M3$DV[M3$LML==i], PA=M3$PA[M3$LML==i], val=M3$value[M3$LML==i])
      if(sum(mt2$val)==0){
        assign(paste("p", j, sep=""), plot_ly(mt2, x = ~DV, y = ~PA, color = 1, colors = "gray", showlegend=FALSE) %>% layout(xaxis = list(range = c(0, dim(struc3d)[1])), yaxis = list(range = c(0, dim(struc3d)[2]))) %>% hide_colorbar())
      }else{
        assign(paste("p", j, sep=""), plot_ly(mt2, x = ~DV, y = ~PA, color = ~val, colors = my_palette2, showlegend=FALSE) %>% layout(xaxis = list(range = c(0, dim(struc3d)[1])), yaxis = list(range = c(0, dim(struc3d)[3]))) %>% colorbar(limits = c(0,log10(max(struc3d)))) %>% hide_colorbar())
      }
      j=j+1
    }
    varlist<-ls(pattern="p[[:digit:]]")
    plotlistDVxPA<-list()
    for(i in 1:length(varlist)){
      plotlistDVxPA[[i]]<-get(varlist[i])
    }
    
    rm(list=varlist)
    j=1
    for(i in seq(1, max(M3$DV), 10)){
      mt2<-data.frame(LML=M3$LML[M3$DV==i], PA=M3$PA[M3$DV==i], val=M3$value[M3$DV==i])
      if(sum(mt2$val)==0){
        assign(paste("p", j, sep=""), plot_ly(mt2, x = ~LML, y = ~PA, color = 1, colors = "gray", showlegend=FALSE) %>% layout(xaxis = list(range = c(0, dim(struc3d)[1])), yaxis = list(range = c(0, dim(struc3d)[2]))) %>% hide_colorbar())
      }else{
        assign(paste("p", j, sep=""), plot_ly(mt2, x = ~LML, y = ~PA, color = ~val, colors = my_palette2, showlegend=FALSE) %>% layout(xaxis = list(range = c(0, dim(struc3d)[2])), yaxis = list(range = c(0, dim(struc3d)[3]))) %>% colorbar(limits = c(0,log10(max(struc3d)))) %>% hide_colorbar())
      }
      j=j+1
    }
    varlist<-ls(pattern="p[[:digit:]]")
    plotlistLMLxPA<-list()
    for(i in 1:length(varlist)){
      plotlistLMLxPA[[i]]<-get(varlist[i])
    }
    projection<-switch(input$projection, DVxLML = plotlistDVxLML, DVxPA = plotlistDVxPA, LMLxPA = plotlistLMLxPA, plotlistDVxLML)
    if(sum(M3$value>0)){
      subplot(projection, nrows=3, titleX = T, shareX = T, shareY = T)
    }
  })
}

shinyApp(ui = ui, server = server)
```